"""Generated by spec2cad from a typed CADProgram.

part:     blower_transition_duct
revision: DesignIntent v2

This file is produced for review. The pipeline does not execute it -- the
executor builds from the typed feature plan directly.
"""

import cadquery as cq
import math

# --- parameters, resolved from DesignIntent ---
duct_inlet_height = 60
duct_inlet_width = 100
duct_outlet_diameter = 80
flange_width = 8
transition_length = 120
wall_thickness = 2.5

# --- feature plan ---
# moulded_transition: thin-wall rectangle-to-round transition
inlet_w = duct_inlet_width
inlet_h = duct_inlet_height
outlet_d = duct_outlet_diameter
transition_l = transition_length
wall_t = wall_thickness
flange_w = flange_width
outer = cq.Workplane('XY').rect(inlet_w, inlet_h).workplane(offset=transition_l).circle(outlet_d/2).loft(combine=False)
inner = (cq.Workplane('XY').workplane(offset=-1).rect(inlet_w-2*wall_t, inlet_h-2*wall_t)
         .workplane(offset=transition_l+2).circle(outlet_d/2-wall_t).loft(combine=False))
result = outer.cut(inner)
inlet_flange = (cq.Workplane('XY').box(inlet_w+2*flange_w, inlet_h+2*flange_w, 5, centered=(True,True,False))
                .cut(cq.Workplane('XY').workplane(offset=-1).box(inlet_w-2*wall_t, inlet_h-2*wall_t, 7, centered=(True,True,False))))
outlet_flange = (cq.Workplane('XY').workplane(offset=transition_l).circle(outlet_d/2+flange_w).extrude(5)
                 .cut(cq.Workplane('XY').workplane(offset=transition_l-1).circle(outlet_d/2-wall_t).extrude(7)))
result = result.union(inlet_flange).union(outlet_flange)

# cq.exporters.export(result.val(), 'part.step')
