"""Generated by spec2cad from a typed CADProgram.

part:     flanged_shaft_coupling
revision: DesignIntent v2

This file is produced for review. The pipeline does not execute it -- the
executor builds from the typed feature plan directly.
"""

import cadquery as cq
import math

# --- parameters, resolved from DesignIntent ---
bolt_circle_diameter = 60
bolt_hole_diameter = 6.6
bore_diameter = 20
entry_chamfer = 1
flange_diameter = 80
flange_thickness = 10
hub_diameter = 40
hub_length = 35
keyway_depth = 3
keyway_width = 6
set_screw_depth = 10

# --- feature plan ---
# coupling_half: keyed rigid-coupling half
flange_d = flange_diameter
flange_t = flange_thickness
hub_d = hub_diameter
hub_l = hub_length
bore_d = bore_diameter
bolt_circle = bolt_circle_diameter
bolt_d = bolt_hole_diameter
key_w = keyway_width
key_d = keyway_depth
set_screw_depth = set_screw_depth
result = (cq.Workplane('XY').circle(flange_d / 2).extrude(flange_t)
          .union(cq.Workplane('XY').workplane(offset=flange_t).circle(hub_d / 2).extrude(hub_l)))
result = result.cut(cq.Workplane('XY').workplane(offset=-1).circle(bore_d / 2).extrude(flange_t + hub_l + 2))
keyway = (cq.Workplane('XY').workplane(offset=-1).center(0, bore_d / 2 + key_d / 2)
          .rect(key_w, key_d).extrude(flange_t + hub_l + 2))
result = result.cut(keyway)
bolt_points = [(bolt_circle / 2 * math.cos(2 * math.pi * i / 4),
                bolt_circle / 2 * math.sin(2 * math.pi * i / 4)) for i in range(4)]
result = result.faces('>Z').workplane().pushPoints(bolt_points).hole(bolt_d)
if set_screw_depth > 0:
    set_screw = cq.Solid.makeCylinder(2.1, set_screw_depth + .2, cq.Vector(hub_d/2 + .1, 0, flange_t + hub_l/2), cq.Vector(-1,0,0))
    result = result.cut(cq.Workplane(obj=set_screw))

# cq.exporters.export(result.val(), 'part.step')
