"""Render a CADProgram as readable CadQuery source, for transparency.

This script is an *output*, not an input. Nothing executes it: the executor
builds from the typed program directly. It exists so a reviewer can read what
the system did in the language they already know, and so the generated geometry
is explicable rather than opaque.

Because it is generated from the same program the executor consumes, it cannot
drift into describing something other than what was built.
"""

from __future__ import annotations

from spec2cad.cad.selectors import EDGE_SELECTOR_SOURCE, FACE_SELECTOR_SOURCE
from spec2cad.schemas.cad_ir import (
    BoxOp,
    CADProgram,
    ChamferOp,
    HoleOp,
    NumberLiteral,
    ParamRef,
    RectangularHolePatternOp,
    Termination,
)


def _expr(numeric, values: dict[str, float]) -> str:
    """Render a Numeric as source, preferring the parameter name."""
    if isinstance(numeric, ParamRef):
        return numeric.ref
    if isinstance(numeric, NumberLiteral):
        return f"{numeric.value:g}"
    return str(numeric)


def write_script(program: CADProgram, values: dict[str, float]) -> str:
    lines: list[str] = [
        '"""Generated by spec2cad from a typed CADProgram.',
        "",
        f"part:     {program.part_name}",
        f"revision: DesignIntent v{program.design_revision}",
        "",
        "This file is produced for review. The pipeline does not execute it -- the",
        "executor builds from the typed feature plan directly.",
        '"""',
        "",
        "import cadquery as cq",
        "",
        "# --- parameters, resolved from DesignIntent ---",
    ]

    used = sorted(program.referenced_parameters)
    for name in used:
        lines.append(f"{name} = {values[name]:g}")
    lines.append("")
    lines.append("# --- feature plan ---")

    first = True
    for op in program.operations:
        if isinstance(op, BoxOp):
            lines.append(
                f"result = (cq.Workplane('XY')"
                f".box({_expr(op.width, values)}, {_expr(op.height, values)}, "
                f"{_expr(op.depth, values)}, centered={op.centered}))"
            )
            first = False
        elif isinstance(op, HoleOp):
            face = FACE_SELECTOR_SOURCE[op.support]
            if op.termination is Termination.THROUGH_ALL:
                lines.append(
                    f"result = (result{face}.workplane(origin=(0, 0, 0))"
                    f".moveTo({_expr(op.x, values)}, {_expr(op.y, values)})"
                    f".circle({_expr(op.diameter, values)} / 2).cutThruAll())"
                    f"   # {op.id}"
                )
            else:
                lines.append(
                    f"result = (result{face}.workplane(origin=(0, 0, 0))"
                    f".moveTo({_expr(op.x, values)}, {_expr(op.y, values)})"
                    f".circle({_expr(op.diameter, values)} / 2)"
                    f".cutBlind(-{_expr(op.depth, values)}))   # {op.id}"
                )
        elif isinstance(op, RectangularHolePatternOp):
            face = FACE_SELECTOR_SOURCE[op.support]
            lines.append(
                f"result = (result{face}.workplane()"
                f".rect({_expr(op.spacing_x, values)}, {_expr(op.spacing_y, values)}, "
                f"forConstruction=True)"
                f".vertices().hole({_expr(op.diameter, values)}))   # {op.id}"
            )
        elif isinstance(op, ChamferOp):
            sel = EDGE_SELECTOR_SOURCE[op.edge_selector]
            lines.append(
                f"result = (result{sel}"
                f".chamfer({_expr(op.distance, values)}))   # {op.id}"
            )
        else:  # pragma: no cover - schema prevents this
            lines.append(f"# unsupported operation: {op!r}")

    lines.extend([
        "",
        "# cq.exporters.export(result.val(), 'part.step')",
        "",
    ])
    return "\n".join(lines)
