"""Render a CADProgram as readable CadQuery source, for transparency.

This script is an *output*, not an input. Nothing executes it: the executor
builds from the typed program directly. It exists so a reviewer can read what
the system did in the language they already know, and so the generated geometry
is explicable rather than opaque.

Because it is generated from the same program the executor consumes, it cannot
drift into describing something other than what was built.
"""

from __future__ import annotations

from spec2cad.cad.selectors import EDGE_SELECTOR_SOURCE, FACE_SELECTOR_SOURCE
from spec2cad.schemas.cad_ir import (
    ArcSegment,
    BlowerTransitionDuctOp,
    BooleanMode,
    BoxOp,
    CADProgram,
    ChamferOp,
    ControllerEnclosureOp,
    CylinderOp,
    CurvedRodOp,
    FilletOp,
    FlangedCouplingOp,
    HoleOp,
    HydraulicManifoldOp,
    LinearSlotPatternOp,
    LineSegment,
    MotorMountBracketOp,
    NumberLiteral,
    ParamRef,
    ProfileExtrudeOp,
    ProfileRevolveOp,
    RectangularHolePatternOp,
    SheetMetalBendOp,
    Termination,
    ThreadedBoltOp,
    TubeOp,
)


def _expr(numeric, values: dict[str, float]) -> str:
    """Render a Numeric as source, preferring the parameter name."""
    if isinstance(numeric, ParamRef):
        return numeric.ref
    if isinstance(numeric, NumberLiteral):
        return f"{numeric.value:g}"
    return str(numeric)


def _profile_source(profile, plane, values: dict[str, float]) -> str:
    start = profile.start
    chain = (
        f"cq.Workplane('{plane.value}').moveTo("
        f"{_expr(start.x, values)}, {_expr(start.y, values)})"
    )
    for segment in profile.segments:
        if isinstance(segment, LineSegment):
            chain += (
                f".lineTo({_expr(segment.end.x, values)}, "
                f"{_expr(segment.end.y, values)})"
            )
        elif isinstance(segment, ArcSegment):
            chain += (
                f".threePointArc((({_expr(segment.midpoint.x, values)}), "
                f"({_expr(segment.midpoint.y, values)})), "
                f"(({_expr(segment.end.x, values)}), "
                f"({_expr(segment.end.y, values)})))"
            )
    return chain + ".close()"


def write_script(program: CADProgram, values: dict[str, float]) -> str:
    lines: list[str] = [
        '"""Generated by spec2cad from a typed CADProgram.',
        "",
        f"part:     {program.part_name}",
        f"revision: DesignIntent v{program.design_revision}",
        "",
        "This file is produced for review. The pipeline does not execute it -- the",
        "executor builds from the typed feature plan directly.",
        '"""',
        "",
        "import cadquery as cq",
        "import math",
        "",
        "# --- parameters, resolved from DesignIntent ---",
    ]

    used = sorted(program.referenced_parameters)
    for name in used:
        lines.append(f"{name} = {values[name]:g}")
    lines.append("")
    lines.append("# --- feature plan ---")

    first = True
    for op in program.operations:
        if isinstance(op, BoxOp):
            lines.append(
                f"result = (cq.Workplane('XY')"
                f".box({_expr(op.width, values)}, {_expr(op.height, values)}, "
                f"{_expr(op.depth, values)}, centered={op.centered}))"
            )
            first = False
        elif isinstance(op, CylinderOp):
            amount = f"{_expr(op.length, values)} / 2"
            lines.append(
                f"result = (cq.Workplane('XY').circle({_expr(op.diameter, values)} / 2)"
                f".extrude({amount}, both={op.centered}))"
            )
            first = False
        elif isinstance(op, TubeOp):
            amount = f"{_expr(op.length, values)} / 2"
            lines.append(
                f"result = (cq.Workplane('XY')"
                f".circle({_expr(op.outer_diameter, values)} / 2)"
                f".circle({_expr(op.inner_diameter, values)} / 2)"
                f".extrude({amount}, both={op.centered}))"
            )
            first = False
        elif isinstance(op, HoleOp):
            face = FACE_SELECTOR_SOURCE[op.support]
            if op.termination is Termination.THROUGH_ALL:
                lines.append(
                    f"result = (result{face}.workplane(origin=(0, 0, 0))"
                    f".moveTo({_expr(op.x, values)}, {_expr(op.y, values)})"
                    f".circle({_expr(op.diameter, values)} / 2).cutThruAll())"
                    f"   # {op.id}"
                )
            else:
                lines.append(
                    f"result = (result{face}.workplane(origin=(0, 0, 0))"
                    f".moveTo({_expr(op.x, values)}, {_expr(op.y, values)})"
                    f".circle({_expr(op.diameter, values)} / 2)"
                    f".cutBlind(-{_expr(op.depth, values)}))   # {op.id}"
                )
        elif isinstance(op, RectangularHolePatternOp):
            face = FACE_SELECTOR_SOURCE[op.support]
            lines.append(
                f"result = (result{face}.workplane()"
                f".rect({_expr(op.spacing_x, values)}, {_expr(op.spacing_y, values)}, "
                f"forConstruction=True)"
                f".vertices().hole({_expr(op.diameter, values)}))   # {op.id}"
            )
        elif isinstance(op, ChamferOp):
            sel = EDGE_SELECTOR_SOURCE[op.edge_selector]
            lines.append(
                f"result = (result{sel}"
                f".chamfer({_expr(op.distance, values)}))   # {op.id}"
            )
        elif isinstance(op, FilletOp):
            sel = EDGE_SELECTOR_SOURCE[op.edge_selector]
            lines.append(
                f"result = (result{sel}"
                f".fillet({_expr(op.radius, values)}))   # {op.id}"
            )
        elif isinstance(op, LinearSlotPatternOp):
            face = FACE_SELECTOR_SOURCE[op.support]
            spacing = _expr(op.spacing, values)
            count = op.count
            lines.append(
                f"slot_points = [(-{spacing} * ({count} - 1) / 2 + i * {spacing}, 0) "
                f"for i in range({count})]"
            )
            lines.append(
                f"result = (result{face}.workplane().pushPoints(slot_points)"
                f".slot2D({_expr(op.length, values)}, {_expr(op.width, values)}, "
                f"{_expr(op.angle_degrees, values)}).cutThruAll())   # {op.id}"
            )
        elif isinstance(op, ProfileExtrudeOp):
            profile = _profile_source(op.profile, op.plane, values)
            amount = f"{_expr(op.distance, values)} / 2" if op.centered else _expr(op.distance, values)
            lines.append(f"feature = ({profile}.extrude({amount}, both={op.centered}, combine=False))")
            if first:
                lines.append("result = feature")
                first = False
            else:
                verb = "union" if op.mode is BooleanMode.ADD else "cut"
                lines.append(f"result = result.{verb}(feature)   # {op.id}")
        elif isinstance(op, ProfileRevolveOp):
            profile = _profile_source(op.profile, op.plane, values)
            a0, a1 = op.axis_start, op.axis_end
            lines.append(
                f"feature = ({profile}.revolve({_expr(op.angle_degrees, values)}, "
                f"axisStart=({_expr(a0.x, values)}, {_expr(a0.y, values)}), "
                f"axisEnd=({_expr(a1.x, values)}, {_expr(a1.y, values)}), combine=False))"
            )
            if first:
                lines.append("result = feature")
                first = False
            else:
                verb = "union" if op.mode is BooleanMode.ADD else "cut"
                lines.append(f"result = result.{verb}(feature)   # {op.id}")
        elif isinstance(op, SheetMetalBendOp):
            lines.extend([
                f"# {op.id}: constant-thickness 90-degree bend",
                f"leg_a = {_expr(op.leg_a, values)}",
                f"leg_b = {_expr(op.leg_b, values)}",
                f"sheet_width = {_expr(op.width, values)}",
                f"sheet_thickness = {_expr(op.thickness, values)}",
                f"inside_radius = {_expr(op.inside_radius, values)}",
                f"k_factor = {_expr(op.k_factor, values)}",
                "outside_radius = inside_radius + sheet_thickness",
                "inner_mid = (outside_radius - inside_radius / 2**0.5, outside_radius - inside_radius / 2**0.5)",
                "outer_mid = (outside_radius - outside_radius / 2**0.5, outside_radius - outside_radius / 2**0.5)",
                "result = (cq.Workplane('XZ').moveTo(outside_radius, 0).lineTo(leg_a, 0)",
                "          .lineTo(leg_a, sheet_thickness).lineTo(outside_radius, sheet_thickness)",
                "          .threePointArc(inner_mid, (sheet_thickness, outside_radius))",
                "          .lineTo(sheet_thickness, leg_b).lineTo(0, leg_b).lineTo(0, outside_radius)",
                "          .threePointArc(outer_mid, (outside_radius, 0)).close()",
                "          .extrude(sheet_width / 2, both=True))",
            ])
            first = False
        elif isinstance(op, CurvedRodOp):
            lines.extend([
                f"# {op.id}: circular section swept along straight–arc–straight centerline",
                f"rod_diameter = {_expr(op.diameter, values)}",
                f"total_length = {_expr(op.total_length, values)}",
                f"bend_start = {_expr(op.bend_start, values)}",
                f"bend_radius = {_expr(op.bend_radius, values)}",
                f"bend_angle = {_expr(op.bend_angle_degrees, values)}",
                "arc_length = bend_radius * math.radians(bend_angle)",
                "tail_length = total_length - bend_start - arc_length",
                "edges = []",
                "if bend_start > 0:",
                "    edges.append(cq.Edge.makeLine(cq.Vector(0, 0, 0), cq.Vector(bend_start, 0, 0)))",
                "arc = cq.Edge.makeCircle(bend_radius, cq.Vector(bend_start, bend_radius, 0),",
                "                         cq.Vector(0, 0, 1), -90, -90 + bend_angle)",
                "edges.append(arc)",
                "if tail_length > 0:",
                "    p = arc.endPoint()",
                "    a = math.radians(bend_angle)",
                "    edges.append(cq.Edge.makeLine(p, cq.Vector(p.x + tail_length * math.cos(a),",
                "                                                    p.y + tail_length * math.sin(a), 0)))",
                "path = cq.Wire.assembleEdges(edges)",
                "result = cq.Workplane('YZ').circle(rod_diameter / 2).sweep(cq.Workplane(obj=path), isFrenet=True)",
            ])
            first = False
        elif isinstance(op, ThreadedBoltOp):
            lines.extend([
                f"# {op.id}: flanged hex bolt with swept helical V-thread",
                f"major_diameter = {_expr(op.major_diameter, values)}",
                f"thread_pitch = {_expr(op.pitch, values)}",
                f"thread_length = {_expr(op.thread_length, values)}",
                f"shank_length = {_expr(op.shank_length, values)}",
                f"head_across_flats = {_expr(op.head_across_flats, values)}",
                f"head_height = {_expr(op.head_height, values)}",
                f"flange_diameter = {_expr(op.flange_diameter, values)}",
                f"flange_thickness = {_expr(op.flange_thickness, values)}",
                "under_head_length = thread_length + shank_length",
                "root_diameter = major_diameter - 1.22687 * thread_pitch",
                "shaft = cq.Workplane('XY').circle(major_diameter / 2).extrude(under_head_length)",
                "helix = cq.Wire.makeHelix(thread_pitch, thread_length, major_diameter / 2)",
                "thread_profile = (cq.Workplane('XZ').moveTo(root_diameter / 2, 0)",
                "                  .lineTo(major_diameter / 2 + 0.4, -thread_pitch * 0.3)",
                "                  .lineTo(major_diameter / 2 + 0.4, thread_pitch * 0.3).close())",
                "thread_cutter = thread_profile.sweep(cq.Workplane(obj=helix), isFrenet=True)",
                "threaded_shaft = shaft.cut(thread_cutter)",
                "flange = (cq.Workplane('XY').workplane(offset=under_head_length)",
                "          .circle(flange_diameter / 2).extrude(flange_thickness))",
                "head_circumscribed_diameter = head_across_flats / math.cos(math.pi / 6)",
                "head = (cq.Workplane('XY').workplane(offset=under_head_length + flange_thickness)",
                "        .polygon(6, head_circumscribed_diameter).extrude(head_height))",
                "result = threaded_shaft.union(flange).union(head)",
            ])
            first = False
        elif isinstance(op, FlangedCouplingOp):
            lines.extend([
                f"# {op.id}: keyed rigid-coupling half",
                f"flange_d = {_expr(op.flange_diameter, values)}",
                f"flange_t = {_expr(op.flange_thickness, values)}",
                f"hub_d = {_expr(op.hub_diameter, values)}",
                f"hub_l = {_expr(op.hub_length, values)}",
                f"bore_d = {_expr(op.bore_diameter, values)}",
                f"bolt_circle = {_expr(op.bolt_circle_diameter, values)}",
                f"bolt_d = {_expr(op.bolt_hole_diameter, values)}",
                f"key_w = {_expr(op.keyway_width, values)}",
                f"key_d = {_expr(op.keyway_depth, values)}",
                f"set_screw_depth = {_expr(op.set_screw_depth, values)}",
                "result = (cq.Workplane('XY').circle(flange_d / 2).extrude(flange_t)",
                "          .union(cq.Workplane('XY').workplane(offset=flange_t).circle(hub_d / 2).extrude(hub_l)))",
                "result = result.cut(cq.Workplane('XY').workplane(offset=-1).circle(bore_d / 2).extrude(flange_t + hub_l + 2))",
                "keyway = (cq.Workplane('XY').workplane(offset=-1).center(0, bore_d / 2 + key_d / 2)",
                "          .rect(key_w, key_d).extrude(flange_t + hub_l + 2))",
                "result = result.cut(keyway)",
                f"bolt_points = [(bolt_circle / 2 * math.cos(2 * math.pi * i / {op.bolt_count}),",
                f"                bolt_circle / 2 * math.sin(2 * math.pi * i / {op.bolt_count})) for i in range({op.bolt_count})]",
                "result = result.faces('>Z').workplane().pushPoints(bolt_points).hole(bolt_d)",
                "if set_screw_depth > 0:",
                "    set_screw = cq.Solid.makeCylinder(2.1, set_screw_depth + .2, cq.Vector(hub_d/2 + .1, 0, flange_t + hub_l/2), cq.Vector(-1,0,0))",
                "    result = result.cut(cq.Workplane(obj=set_screw))",
            ])
            first = False
        elif isinstance(op, ControllerEnclosureOp):
            lines.extend([
                f"# {op.id}: open-top constant-thickness controller enclosure",
                f"length = {_expr(op.length, values)}",
                f"width = {_expr(op.width, values)}",
                f"height = {_expr(op.height, values)}",
                f"sheet_t = {_expr(op.thickness, values)}",
                f"cable_gland_x = {_expr(op.cable_gland_x, values)}",
                f"cable_gland_d = {_expr(op.cable_gland_diameter, values)}",
                "outer = cq.Workplane('XY').box(length, width, height, centered=(True, True, False))",
                "cavity = (cq.Workplane('XY').workplane(offset=sheet_t)",
                "          .box(length - 2*sheet_t, width - 2*sheet_t, height + 1, centered=(True, True, False)))",
                "result = outer.cut(cavity)",
                "display = cq.Workplane('XY').box(44, 2*sheet_t + 2, 18).translate((0, -width/2, height*.58))",
                "result = result.cut(display)",
                "if cable_gland_d > 0:",
                "    gland = cq.Solid.makeCylinder(cable_gland_d/2, 2*sheet_t + 2, cq.Vector(cable_gland_x, -width/2 - 1, 16), cq.Vector(0,1,0))",
                "    result = result.cut(cq.Workplane(obj=gland))",
            ])
            first = False
        elif isinstance(op, MotorMountBracketOp):
            lines.extend([
                f"# {op.id}: gusseted NEMA motor bracket",
                f"bracket_width = {_expr(op.bracket_width, values)}",
                f"base_depth = {_expr(op.base_depth, values)}",
                f"base_t = {_expr(op.base_thickness, values)}",
                f"face_height = {_expr(op.face_height, values)}",
                f"motor_spacing = {_expr(op.motor_spacing, values)}",
                f"mount_hole_d = {_expr(op.mounting_hole_diameter, values)}",
                f"shaft_hole_d = {_expr(op.shaft_hole_diameter, values)}",
                "base = cq.Workplane('XY').box(bracket_width, base_depth, base_t, centered=(True, True, False))",
                "wall_y = base_depth/2 - base_t/2",
                "wall = (cq.Workplane('XY').box(bracket_width, base_t, face_height+.5, centered=(True,True,False))",
                "        .translate((0, wall_y, base_t-.5)))",
                "result = base.union(wall)",
                "face_z = base_t + face_height/2",
                "cutters = [cq.Solid.makeCylinder(shaft_hole_d/2, 4*base_t, cq.Vector(0, base_depth/2-2*base_t, face_z), cq.Vector(0,1,0))]",
                "for x in (-motor_spacing/2, motor_spacing/2):",
                "    for z in (face_z-motor_spacing/2, face_z+motor_spacing/2):",
                "        cutters.append(cq.Solid.makeCylinder(mount_hole_d/2, 4*base_t, cq.Vector(x, base_depth/2-2*base_t, z), cq.Vector(0,1,0)))",
                "for cutter in cutters: result = result.cut(cq.Workplane(obj=cutter))",
                f"result = result.faces('>Z').workplane().pushPoints([(-bracket_width*.28, -base_depth*.2), (bracket_width*.28, -base_depth*.2)]).slot2D({_expr(op.slot_length, values)}, {_expr(op.slot_width, values)}, 90).cutThruAll()",
            ])
            first = False
        elif isinstance(op, HydraulicManifoldOp):
            lines.extend([
                f"# {op.id}: threaded ports and connected cross-drillings",
                f"block_l = {_expr(op.length, values)}",
                f"block_w = {_expr(op.width, values)}",
                f"block_h = {_expr(op.height, values)}",
                f"port_major = {_expr(op.port_major_diameter, values)}",
                f"port_minor = {_expr(op.port_minor_diameter, values)}",
                f"port_pitch = {_expr(op.port_pitch, values)}",
                f"tap_depth = {_expr(op.tapping_depth, values)}",
                f"passage_d = {_expr(op.passage_diameter, values)}",
                f"port_spacing = {_expr(op.port_spacing, values)}",
                "result = cq.Workplane('XY').box(block_l, block_w, block_h)",
                "for x in (-port_spacing/2, port_spacing/2):",
                "    bore = cq.Workplane('XY').workplane(offset=block_h/2-tap_depth).center(x,0).circle(port_minor/2).extrude(tap_depth+.5)",
                "    helix = cq.Wire.makeHelix(port_pitch, tap_depth, port_minor/2).translate(cq.Vector(x,0,block_h/2-tap_depth))",
                "    thread_profile = (cq.Workplane('XZ').transformed(offset=(x,0,block_h/2-tap_depth))",
                "                      .moveTo(port_minor/2,0).lineTo(port_major/2+.2,-port_pitch*.3)",
                "                      .lineTo(port_major/2+.2,port_pitch*.3).close())",
                "    result = result.cut(bore.union(thread_profile.sweep(cq.Workplane(obj=helix), isFrenet=True)))",
            ])
            first = False
        elif isinstance(op, BlowerTransitionDuctOp):
            lines.extend([
                f"# {op.id}: thin-wall rectangle-to-round transition",
                f"inlet_w = {_expr(op.inlet_width, values)}",
                f"inlet_h = {_expr(op.inlet_height, values)}",
                f"outlet_d = {_expr(op.outlet_diameter, values)}",
                f"transition_l = {_expr(op.transition_length, values)}",
                f"wall_t = {_expr(op.wall_thickness, values)}",
                f"flange_w = {_expr(op.flange_width, values)}",
                "outer = cq.Workplane('XY').rect(inlet_w, inlet_h).workplane(offset=transition_l).circle(outlet_d/2).loft(combine=False)",
                "inner = (cq.Workplane('XY').workplane(offset=-1).rect(inlet_w-2*wall_t, inlet_h-2*wall_t)",
                "         .workplane(offset=transition_l+2).circle(outlet_d/2-wall_t).loft(combine=False))",
                "result = outer.cut(inner)",
                "inlet_flange = (cq.Workplane('XY').box(inlet_w+2*flange_w, inlet_h+2*flange_w, 5, centered=(True,True,False))",
                "                .cut(cq.Workplane('XY').workplane(offset=-1).box(inlet_w-2*wall_t, inlet_h-2*wall_t, 7, centered=(True,True,False))))",
                "outlet_flange = (cq.Workplane('XY').workplane(offset=transition_l).circle(outlet_d/2+flange_w).extrude(5)",
                "                 .cut(cq.Workplane('XY').workplane(offset=transition_l-1).circle(outlet_d/2-wall_t).extrude(7)))",
                "result = result.union(inlet_flange).union(outlet_flange)",
            ])
            first = False
        else:  # pragma: no cover - schema prevents this
            lines.append(f"# unsupported operation: {op!r}")

    lines.extend([
        "",
        "# cq.exporters.export(result.val(), 'part.step')",
        "",
    ])
    return "\n".join(lines)
