"""Generated by spec2cad from a typed CADProgram.

part:     sheet_metal_controller_enclosure
revision: DesignIntent v2

This file is produced for review. The pipeline does not execute it -- the
executor builds from the typed feature plan directly.
"""

import cadquery as cq
import math

# --- parameters, resolved from DesignIntent ---
cable_gland_diameter = 20
cutout_position = 40
enclosure_height = 40
enclosure_length = 120
enclosure_width = 80
sheet_thickness = 1.5

# --- feature plan ---
# folded_enclosure: open-top constant-thickness controller enclosure
length = enclosure_length
width = enclosure_width
height = enclosure_height
sheet_t = sheet_thickness
cable_gland_x = cutout_position
cable_gland_d = cable_gland_diameter
outer = cq.Workplane('XY').box(length, width, height, centered=(True, True, False))
cavity = (cq.Workplane('XY').workplane(offset=sheet_t)
          .box(length - 2*sheet_t, width - 2*sheet_t, height + 1, centered=(True, True, False)))
result = outer.cut(cavity)
display = cq.Workplane('XY').box(44, 2*sheet_t + 2, 18).translate((0, -width/2, height*.58))
result = result.cut(display)
if cable_gland_d > 0:
    gland = cq.Solid.makeCylinder(cable_gland_d/2, 2*sheet_t + 2, cq.Vector(cable_gland_x, -width/2 - 1, 16), cq.Vector(0,1,0))
    result = result.cut(cq.Workplane(obj=gland))

# cq.exporters.export(result.val(), 'part.step')
