"""Generated by spec2cad from a typed CADProgram.

part:     adjustable_motor_mount_bracket
revision: DesignIntent v1

This file is produced for review. The pipeline does not execute it -- the
executor builds from the typed feature plan directly.
"""

import cadquery as cq
import math

# --- parameters, resolved from DesignIntent ---
base_depth = 60
base_thickness = 8
bracket_width = 38
face_height = 60
gusset_thickness = 5
motor_spacing = 31
mounting_hole_diameter = 4.5
shaft_hole_diameter = 24
slot_length = 28
slot_width = 8

# --- feature plan ---
# gusseted_motor_bracket: gusseted NEMA motor bracket
bracket_width = bracket_width
base_depth = base_depth
base_t = base_thickness
face_height = face_height
motor_spacing = motor_spacing
mount_hole_d = mounting_hole_diameter
shaft_hole_d = shaft_hole_diameter
base = cq.Workplane('XY').box(bracket_width, base_depth, base_t, centered=(True, True, False))
wall_y = base_depth/2 - base_t/2
wall = (cq.Workplane('XY').box(bracket_width, base_t, face_height+.5, centered=(True,True,False))
        .translate((0, wall_y, base_t-.5)))
result = base.union(wall)
face_z = base_t + face_height/2
cutters = [cq.Solid.makeCylinder(shaft_hole_d/2, 4*base_t, cq.Vector(0, base_depth/2-2*base_t, face_z), cq.Vector(0,1,0))]
for x in (-motor_spacing/2, motor_spacing/2):
    for z in (face_z-motor_spacing/2, face_z+motor_spacing/2):
        cutters.append(cq.Solid.makeCylinder(mount_hole_d/2, 4*base_t, cq.Vector(x, base_depth/2-2*base_t, z), cq.Vector(0,1,0)))
for cutter in cutters: result = result.cut(cq.Workplane(obj=cutter))
result = result.faces('>Z').workplane().pushPoints([(-bracket_width*.28, -base_depth*.2), (bracket_width*.28, -base_depth*.2)]).slot2D(slot_length, slot_width, 90).cutThruAll()

# cq.exporters.export(result.val(), 'part.step')
