"""Generated by spec2cad from a typed CADProgram.

part:     motor_adapter_plate
revision: DesignIntent v2

This file is produced for review. The pipeline does not execute it -- the
executor builds from the typed feature plan directly.
"""

import cadquery as cq

# --- parameters, resolved from DesignIntent ---
external_chamfer = 1
hole_spacing_x = 31
hole_spacing_y = 31
mounting_hole_diameter = 3.4
plate_height = 50
plate_thickness = 5
plate_width = 45
shaft_opening_diameter = 22.5

# --- feature plan ---
result = (cq.Workplane('XY').box(plate_width, plate_height, plate_thickness, centered=True))
result = (result.faces(">Z").workplane(origin=(0, 0, 0)).moveTo(0, 0).circle(shaft_opening_diameter / 2).cutThruAll())   # shaft_opening
result = (result.faces(">Z").workplane().rect(hole_spacing_x, hole_spacing_y, forConstruction=True).vertices().hole(mounting_hole_diameter))   # mounting_holes
result = (result.edges("|Z").edges(ExternalVerticalEdges(width, height)).chamfer(external_chamfer))   # external_chamfers

# cq.exporters.export(result.val(), 'part.step')
