"""Backend-neutral build contracts and adapter boundaries."""

from .contracts import (
    BACKEND_PROTOCOL_SCHEMA_VERSION,
    ArtifactKind,
    ArtifactManifest,
    BackendDiagnostic,
    BackendDiagnosticCode,
    BackendOperation,
    BuildRequest,
    BuildResult,
    BuildStatus,
    DiagnosticSeverity,
    RecomputeState,
    StateSnapshot,
    StateStatus,
)
from .protocol import (
    AdapterDescriptor,
    BackendOperationResult,
    CADBackend,
    ExportRequest,
    InspectRequest,
    OperationStatus,
    ReimportVerificationRequest,
    unsupported_operation_result,
)
from .freecad_worker_contracts import (
    FREECAD_WORKER_SCHEMA_VERSION,
    FreeCADWorkerDiagnostic,
    FreeCADWorkerOperation,
    FreeCADWorkerRequest,
    FreeCADWorkerResponse,
    FreeCADFeatureSummary,
    FreeCADNativeBuildSummary,
    FreeCADSketchSummary,
    WorkerStatus,
)

__all__ = [
    "BACKEND_PROTOCOL_SCHEMA_VERSION",
    "ArtifactKind",
    "ArtifactManifest",
    "BackendDiagnostic",
    "BackendDiagnosticCode",
    "BackendOperation",
    "BuildRequest",
    "BuildResult",
    "BuildStatus",
    "DiagnosticSeverity",
    "RecomputeState",
    "StateSnapshot",
    "StateStatus",
    "AdapterDescriptor",
    "BackendOperationResult",
    "CADBackend",
    "ExportRequest",
    "InspectRequest",
    "OperationStatus",
    "ReimportVerificationRequest",
    "unsupported_operation_result",
    "FREECAD_WORKER_SCHEMA_VERSION",
    "FreeCADWorkerDiagnostic",
    "FreeCADWorkerOperation",
    "FreeCADWorkerRequest",
    "FreeCADWorkerResponse",
    "FreeCADFeatureSummary",
    "FreeCADNativeBuildSummary",
    "FreeCADSketchSummary",
    "WorkerStatus",
]
