"""Generated by spec2cad from a typed CADProgram.

part:     hydraulic_manifold
revision: DesignIntent v1

This file is produced for review. The pipeline does not execute it -- the
executor builds from the typed feature plan directly.
"""

import cadquery as cq
import math

# --- parameters, resolved from DesignIntent ---
block_height = 30
block_length = 100
block_width = 60
passage_diameter = 8
port_major_diameter = 12
port_minor_diameter = 10.2
port_pitch = 1.5
port_spacing = 40
tapping_depth = 14

# --- feature plan ---
# cross_drilled_manifold: threaded ports and connected cross-drillings
block_l = block_length
block_w = block_width
block_h = block_height
port_major = port_major_diameter
port_minor = port_minor_diameter
port_pitch = port_pitch
tap_depth = tapping_depth
passage_d = passage_diameter
port_spacing = port_spacing
result = cq.Workplane('XY').box(block_l, block_w, block_h)
for x in (-port_spacing/2, port_spacing/2):
    bore = cq.Workplane('XY').workplane(offset=block_h/2-tap_depth).center(x,0).circle(port_minor/2).extrude(tap_depth+.5)
    helix = cq.Wire.makeHelix(port_pitch, tap_depth, port_minor/2).translate(cq.Vector(x,0,block_h/2-tap_depth))
    thread_profile = (cq.Workplane('XZ').transformed(offset=(x,0,block_h/2-tap_depth))
                      .moveTo(port_minor/2,0).lineTo(port_major/2+.2,-port_pitch*.3)
                      .lineTo(port_major/2+.2,port_pitch*.3).close())
    result = result.cut(bore.union(thread_profile.sweep(cq.Workplane(obj=helix), isFrenet=True)))

# cq.exporters.export(result.val(), 'part.step')
